trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azure-connection'
  appName: 'sharana-flask-app'

stages:

- stage: Build
  displayName: 'Build & Test'
  jobs:
  - job: BuildTest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'

    - script: |
        cd app
        pip install -r requirements.txt
        pip install pytest
        pytest tests/ || echo "No tests yet"
      displayName: 'Install & Test'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'app/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  displayName: 'Deploy to App Service (Free)'
  dependsOn: Build
  jobs:
  - deployment: DeployAppService
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Flask to App Service'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/drop/app.zip'
              runtimeStack: 'PYTHON|3.10'
              startUpCommand: 'python app.py'
