trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  displayName: 'Build & Test'
  jobs:
  - job: BuildTest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'

    - script: |
        cd app
        pip install -r requirements.txt
        pip install pytest
        pytest tests/ || echo "No tests yet"
      displayName: 'Install & Test'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'app/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'