pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    ECR_REPO = "897729139530.dkr.ecr.ap-south-1.amazonaws.com/flask-devops"
  }

  stages {

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t flask-devops ./app'
      }
    }

    stage('Login to ECR') {
      steps {
        withAWS(credentials: 'aws-creds', region: AWS_REGION) {
          sh '''
            aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $ECR_REPO
          '''
        }
      }
    }

    stage('Push Image to ECR') {
      steps {
        sh '''
          docker tag flask-devops:latest $ECR_REPO:latest
          docker push $ECR_REPO:latest
        '''
      }
    }

    stage('Deploy to EKS') {
      steps {
        sh 'kubectl apply -f k8s/'
      }
    }
  }
}
